config/routes.rb
Rails.application.routes.draw do
  get 'cycle_tracker/index'

  resources :rides
  resources :bikes

  root 'cycle_tracker#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bike.rb
class Bike < ApplicationRecord
end

app/models/ride.rb
class Ride < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def new

  end
  def create
    @bike =  Bike.new(bike_params)

    @bike.save
    redirect_to @bike
  end

  def show

  end

  private
  def bike_params
    params.require(:bike).permit(:BikeName)
  end
end

app/controllers/cycle_tracker_controller.rb
class CycleTrackerController < ApplicationController
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def new
    @bikeList=Bike.all
  end

  def create
    @ride = Ride.new (ride_params)
    @ride.save

    redirect_to @ride
  end

  def show

  end

  private
  def ride_params
    params.require(:Ride).permit(:BikeID, :RideDate, :TimeInMinutes, :TimeInHours, :DistanceInMiles, :DistanceInKm, :Ascent)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def datepicker_input form, field
    content_tag :td, :data => {:provide => 'datepicker', 'date-format' => 'yyyy-mm-dd', 'date-autoclose' => 'true'} do
      form.text_field field, class: 'form-control', placeholder: 'DD/MM/YYYY'
    end
  end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/cycle_tracker_helper.rb
module CycleTrackerHelper
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/bikes/new.html.erb
<%= form_with scope: :bike, url: bikes_path, local: true do |form| %>
  <p>
    <%= form.label :'Bike Name' %><br>
    <%= form.text_field :BikeName %>
  </p>

  <p>
    <%= form.submit %>
    <%= link_to 'Back', cycle_tracker_index_path%>
  </p>
<% end %>

app/views/cycle_tracker/index.html.erb
<%= link_to 'Add new Bike', new_bike_path %>
<br>
<%= link_to 'Add new Ride', new_ride_path %>

app/views/rides/new.html.erb
<%= form_with scope: :ride, url: rides_path, local: true do |form| %>
  <p>
    <% options = options_from_collection_for_select(@bikeList, 'BikeID', 'BikeName') %>
    <%= form.label :'Bike' %>
    <%= form.select :BikeID, options %>
  </p>


  <p>
    <%= form.label :'Ride Date' %><br>
    <%= datepicker_input form, :RideDate%>
  </p>

  <p>
    <%= form.label :'Distance in Miles' %><br>
    <%= form.number_field :DistanceInMiles, step: :any %>
  </p>

  <p>
    <%= form.label :'Distance in Km' %><br>
    <%= form.number_field :DistanceInKm, step: :any %>
  </p>

  <p>
    <%= form.label :'Time in minutes' %><br>
    <%= form.number_field :TimeInMinutes, step: :any %>
  </p>

  <p>
    <%= form.label :'Time in Hours' %><br>
    <%= form.number_field :TimeInHours, step: :any %>
  </p>

  <p>
    <%= form.label :'Ascent' %><br>
    <%= form.number_field :Ascent %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>